### ISSUE TITLE
About your fine plugin

### ISSUE THREAD

**Issue by sanayar2008** [davideperozzi/momentum-js-page#1]
if this momentum chrome plugin clone.

I need to add currency today rate on the right corner of the tab .
I need to add momentum pro (plan)

so what does it cost & time ?

**Comment by davideperozzi** [comment]
Sorry, what exactly are you asking for?

**Comment by sanayar2008** [comment]
I want to a clone of chrome (momentum) plugin one.?
could you able to create this one for me ? if yeas, what does it cost & time ?

**Comment by davideperozzi** [comment]
I don't think this is the plugin you're referring to. Also I'm not working on chrome plugins.

**Comment by davideperozzi** [comment]
I don't think this is the plugin you're referring to. Also I'm not working on chrome plugins.
